### ISSUE TITLE
Remote schema

### ISSUE THREAD

**Issue by joshua1** [jycouet/kitql#107]
All examples or videos so far have been done with local schema , is there any out there with remote schema and introspection? each time i try modifying the graphql yaml file to point to a remote schema with header information (based on the commented out section of that file in the examples, its always some schema error

**Comment by notrab** [comment]
Hey @joshua1 

You can provide the URL to the remote API similar to how I do with my configuration here:

```yaml
projects:
  default:
    schema: ${VITE_GRAPHQL_ENDPOINT}
    documents:
      - '**/*.{graphql,gql}'
    extensions:
      endpoints:
        default:
          url: ${VITE_GRAPHQL_ENDPOINT}
      codegen:
        generates:
          ./src/lib/graphql/_kitql/graphqlTypes.ts:
            plugins:
              - typescript
              - typescript-operations
              - typed-document-node
              - typescript-document-nodes
          ./src/lib/graphql/_kitql/graphqlStores.ts:
            plugins:
              - '@kitql/graphql-codegen'
            config:
              importBaseTypesFrom: $lib/graphql/_kitql/graphqlTypes

        config:
          useTypeImports: true
```

You'll notice I'm using `${}` to fetch from `.env`

To do this you'll need to update `package.json` to include `--require dotenv/config` where you call `graphql-codegen`:

```json
"scripts": {
  "generate": "graphql-codegen --require dotenv/config"
}
```

Then inside `.env`, that looks like: VITE_GRAPHQL_ENDPOINT=https://api.cartql.com
