### ISSUE TITLE
types are not imported into graphqlStores.ts

### ISSUE THREAD

**Issue by gregoryforel** [jycouet/kitql#108]
Hello!

I just put together a `graphqlrc.yaml` config as per the tutorial, and when running yarn gen, the files are generated.

Having a closer look at `graphqlStores.ts`, I noticed that the types used in the files aren't imported, therefore ESLint is complaining.

Is that something you came across before?

**Comment by jycouet** [comment]
No, types should work. It's the main point of using codegen 👍
I guess that you are missing something in the configuration.

Could you post here your `graphqlrc.yaml`?

**Comment by gregoryforel** [comment]
So, types _are_ created, however, they aren't imported.

Here's the `yaml` file
```yaml
schema:
  - ./src/lib/data-access/graphql/schema.json
documents:
  - './src/**/*.{gql,graphql}'
generates:
  ./src/lib/data-access/graphql/_kitql/graphqlTypes.ts:
    plugins:
      - typescript
      - typescript-operations
      - typed-document-node
      - typescript-document-nodes

  ./src/lib/data-access/graphql/_kitql/graphqlStores.ts:
    plugins:
      - '@kitql/graphql-codegen'
```

Once generated, I have:
`graphql/_kitql/graphqlStores.ts`
`graphql/_kitql/graphqlTypes.ts`

In the following file, you'll see that types such as `ModifyCvMutationVariables` are not imported, although they do exist inside `graphqlTypes.ts`.
**graphqlStores.ts**
```typescript
import { browser } from '$app/env';
import { defaultStoreValue, RequestStatus, ResponseResultType, type PatchType, type RequestParameters, type RequestQueryParameters, type RequestResult } from '@kitql/client';
import { get, writable } from 'svelte/store';
import { kitQLClient } from '../kitQLClient';
 
/**
 * Init KitQL (to have clientStarted = true!)
 *
 * Waiting for: https://github.com/sveltejs/kit/issues/4447
 */
export function KQL__Init() {}
 
/* Internal. To skip await on a client side navigation in the load function (from queryLoad)! */
let clientStarted = false; // Will be true on a client side navigation
if (browser) {
	addEventListener('sveltekit:start', () => {
		clientStarted = true;
	});
}
 
/**
 * ResetAllCaches in One function!
 */
export function KQL__ResetAllCaches() {
}
 
/* Operations 👇 */
function KQL_ModifyCvStore() {
	const operationName = 'KQL_ModifyCv';
	const operationType = ResponseResultType.Mutation;

	// prettier-ignore
	const { subscribe, set, update } = writable<RequestResult<ModifyCvMutation, ModifyCvMutationVariables>>({...defaultStoreValue, operationName, operationType});

		async function mutateLocal(
			params?: RequestParameters<ModifyCvMutationVariables>
		): Promise<RequestResult<ModifyCvMutation, ModifyCvMutationVariables>> {
...
```

**Comment by jycouet** [comment]
If you add the config: `importBaseTypesFrom: $lib/graphql/_kitql/graphqlTypes` like in the example, your types will be imported correctly.

Check: https://github.com/jycouet/kitql/blob/main/examples/demo1/.graphqlrc.yaml#L31

If it's working well, I let you close the issue. 👍

**Comment by gregoryforel** [comment]
Thanks! I originally followed the [all-in tutorial](https://kitql.vercel.app/docs/all-in), and it doesn't have the `importBaseTypesFrom: $lib/graphql/_kitql/graphqlTypes` config. It works

**Comment by gregoryforel** [comment]
Thank you for the lib. While you're at it, some quick notes:
* I originally copied/paste the code from the all in tutorial. I had an error message saying that `codegen` was not indented properly.
* Once I corrected the indentation (so `codegen` is at the same level as `documents`, the config failed me with 
```shell
Invalid Codegen Configuration!

        Please make sure that your codegen config file contains the "generates" field, with
 a specification for the plugins you need.

        It should looks like that:

        schema:
          - my-schema.graphql
        generates:
          my-file.ts:
            - plugin1
            - plugin2
            - plugin3
```

I ended up simplifying the config to:
```yaml
schema:
  - ./src/lib/data-access/graphql/schema.json
documents:
  - './src/**/*.{gql,graphql}'
generates:
  ./src/lib/data-access/graphql/_kitql/graphqlTypes.ts:
    plugins:
      - typescript
      - typescript-operations
      - typed-document-node
      - typescript-document-nodes

  ./src/lib/data-access/graphql/_kitql/graphqlStores.ts:
    plugins:
      - '@kitql/graphql-codegen'
    config:
      importBaseTypesFrom: $lib/data-access/graphql/_kitql/graphqlTypes
```
