### ISSUE TITLE
Syntax error for generated imports

### ISSUE THREAD

**Issue by Nukiloco** [jycouet/kitql#173]
### Describe the bug

Having this ``.kitql.yaml``
```
generates:
  ./src/lib/server/gen/kitql:
    modules:
      - ./src/lib/server/modules/*
    actions:
      # createEnumsModule:
      #   prismaFile: ./prisma/schema.prisma
      mergeModuleTypedefs: true
      mergeModuleResolvers: true
      mergeContexts: true
      mergeModules: true

    moduleOutputFolder: gen/kitql
    importBaseTypesFrom: ./src/lib/server/server/gen/graphql-base-types.ts
```
with this file layout
- src
  - lib
    - server
      - modules
        - user
          - db
            - prisma files 
          - gen
            - generated files
          - resolvers
            - typescript files
          - schema
            - typedef gql files

is producing this file output
``_appModules.ts``
```
import { userModule } from '..\..\modules\user';

export const modules = [
  userModule,
];
```

which produces this error
```
C:/Users/user/Desktop/Nukiloco/Projects/Project/full/src/lib/server/gen/kitql/_appModules.ts:1:43: ERROR: Syntax error "s"


[33mSyntax error "s"[39m
1  |  import { userModule } from '..\..\modules\user';
   |                                             ^
2  |  
3  |  export const modules = [

```

### Your Example Website or App

local

### Steps to Reproduce the Bug or Issue

Described above

### Expected behavior

I expected it to not return the error above when going to http://localhost:8000/api/graphql

### Platform

- OS: Windows
- NodeJS: 16.14.1
- `@kitql/*` version: ^0.7.0

### Additional context

I will probably fill in the rest of the information of the bug report later. I'm very tired right now.
