### ISSUE TITLE
Resolvers path only use .../ once

### ISSUE THREAD

**Issue by Nukiloco** [jycouet/kitql#176]
### Describe the bug

I have done more testing and resolvers only escape the parent one time currently, which means if you set the generated folder of kitql to be in something like ``gen/kitql`` then you will get errors in the generated resolver files.

I believe the errors are happening on this line
https://github.com/jycouet/kitql/blob/main/packages/module-codegen/src/actionResolvers.ts#L12

current config file:
```
generates:
  ./src/lib/server/gen/kitql:
    modules:
      - ./src/lib/server/modules/*
    actions:
      # createEnumsModule:
      #   prismaFile: ./prisma/schema.prisma
      mergeModuleTypedefs: true
      mergeModuleResolvers: true
      mergeContexts: true
      mergeModules: true

    moduleOutputFolder: gen/kitql
    importBaseTypesFrom: ./src/lib/server/server/gen/graphql-base-types.ts
```

wrong output:
```
import { resolvers as mutation } from '../resolvers/mutation';
import { resolvers as query } from '../resolvers/query';
import { resolvers as scalar } from '../resolvers/scalar';

export const resolvers = [
  mutation,
  query,
  scalar,
];
```

### Your Example Website or App

local

### Steps to Reproduce the Bug or Issue

Described above

### Expected behavior

I expect the generation behavior to not generate an incorrect path.

```
import { resolvers as mutation } from '../../resolvers/mutation';
import { resolvers as query } from '../../resolvers/query';
import { resolvers as scalar } from '../../resolvers/scalar';

export const resolvers = [
  mutation,
  query,
  scalar,
];
```

### Platform

Windows 10

### Additional context

I think the best option is to reuse the code from ``path.join(moduleFolder, resolversFolder)

Just a quick hack here to fix this:
```
    const resolversFolder = 'resolvers';

    let kitqlModuleFolder = path.join(moduleFolder, moduleOutputFolder)

    const resolversPath = path.join(moduleFolder, resolversFolder)
    const resolversPathImport = toForwardSlash(path.relative(kitqlModuleFolder, resolversPath))
    const resolversFiles = getFiles(resolversPath);

    const dataResolvers = [];
    resolversFiles.forEach(resolver => {
        dataResolvers.push(`import { resolvers as ${getFileWODots(resolver)} } from '${resolversPathImport}/${getFileWOTS(resolver)}';`);
    });
```
